# version: '3.9' - Obsolete

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - backend_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes: # Pgadmin volume for data persistance
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - frontend_net
      - backend_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - backend_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "${KAFKA_EXTERNAL_PORT}:9092"
    networks:
      - backend_net

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:${KAFKA_EXTERNAL_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    healthcheck:
      test: ["CMD", "bash", "-c", "cub kafka-ready -b localhost:9092 1 20"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy  # Kafka UI should depend on Kafka, otherwise Kafka UI may start before Kafka is ready and failed to connect
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - backend_net
      - frontend_net

  api:
    container_name: api
    build: ./api
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - postgres
    networks:
      - backend_net
      - frontend_net

  ui:
    image: nginx
    container_name: ui
    volumes:
      - ./ui:/usr/share/nginx/html
    ports:
      - "${UI_PORT}:80"
    networks:
      - frontend_net

  producer:
    container_name: producer
    build: ./producer
    stdin_open: true
    tty: true
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend_net

  consumer:
    container_name: consumer
    build: ./consumer
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend_net

volumes: # Declare named volumes
  postgres_data:
  pgadmin_data:

networks: # Declare named networks
  backend_net:
    driver: bridge
  frontend_net:
    driver: bridge